hello = "Hello~ {{.v0}}"
loggedinas = "ãƒ­ã‚°ã‚¤ãƒ³ã—ã¦ã„ã¾ã™ {{.v0}}"
titleprefix = "inter.tube - "

email = "ãƒ¡ãƒ¼ãƒ«ã‚¢ãƒ‰ãƒ¬ã‚¹"
password = "ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰"
passwordconfirm = "ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰ (ç¢ºèª)"
currentpassword = "ç¾åœ¨ã®ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰"
newpassword = "æ–°ã—ã„ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰"
newpasswordconfirm = "æ–°ã—ã„ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰ (ç¢ºèª)"
login = "ãƒ­ã‚°ã‚¤ãƒ³"
logout = "ãƒ­ã‚°ã‚¢ã‚¦ãƒˆ"
register = "ç™»éŒ²"
invitecode = "æ‹›å¾…ã‚³ãƒ¼ãƒ‰"
theme = "UIãƒ†ãƒ¼ãƒ"
noscript = "Javascriptã‚’æœ‰åŠ¹ã«ã—ã¦ãã ã•ã„ã€‚ç„¡åŠ¹ã ã¨ã‚µã‚¤ãƒˆãŒå£Šã‚Œã¡ã‚ƒã„ã¾ã™ã€‚ã‚¢ãƒŠãƒªãƒ†ã‚£ã‚¯ã‚¹ã‚„ãƒˆãƒ©ãƒƒã‚­ãƒ³ã‚°ã¯ä¸€åˆ‡ãªã„ã®ã§ã”å®‰å¿ƒãã ã•ã„"

edit = "ç·¨é›†"
update = "æ›´æ–°"
status = "ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹"
expired = "æœŸé™åˆ‡ã‚Œ"
canceled = "ã‚­ãƒ£ãƒ³ã‚»ãƒ«æ¸ˆã¿"
expires = "æœ‰åŠ¹æœŸé™"

track = "æ›²"
nowplaying = "å†ç”Ÿä¸­: "
artist = "ã‚¢ãƒ¼ãƒ†ã‚£ã‚¹ãƒˆ"
albumartist = "ã‚¢ãƒ«ãƒãƒ ã‚¢ãƒ¼ãƒ†ã‚£ã‚¹ãƒˆ"
composer = "ä½œæ›²è€…"
album = "ã‚¢ãƒ«ãƒãƒ "
title = "æ›²å"
cover = "ã‚«ãƒãƒ¼å†™çœŸ"
comment = "ã‚³ãƒ¡ãƒ³ãƒˆ"
filesize = "ãƒ•ã‚¡ã‚¤ãƒ«ã‚µã‚¤ã‚º"
format = "ãƒ•ã‚©ãƒ¼ãƒãƒƒãƒˆ"
total = "å…¨"
disc = "disc"
discs = "discs"
year = "å¹´"
tags = "ã‚¿ã‚°"
none = "(ãªã—)"

usage = "usage"
currentusage = "current usage"
quota = "quota"
supportedformats = "mp3, flac, m4a"

# nav bar
nav_index = "home"
nav_music = "music"
nav_upload = "upload"
nav_logout = "logout"
nav_forum = "forum"
nav_more = "more"
nav_settings = "settings"
nav_musiclib = "music library"
# logged out
nav_login = "log in"
nav_register = "register"
nav_pricing = "pricing"
# footer
nav_tos = "terms of service"
nav_privacy = "privacy policy"

# login
login_title = "welcome to inter.tube"
login_needreg = "no account?"
login_toreg = "register here"
login_forgot = "forgot password?"
login_toforgot = "reset your password here"
login_cookies = "cookie notice: this site uses cookies solely to provide access to your account, never to track you or show you ads. we actually care about your privacy. that's why we don't need a big annoying cookie banner."
login_cookies2 = "files are hosted via cloudflare. they may set anonymized cookies to prevent network abuse. these cookies do not allow for cross-site tracking or correspond to your ID."
login_cookiescf = "more info"
login_nevermind = "nevermind, back to login page"

# intro
intro_what = "what's this?"
intro_explain = "this is inter.tube, a place where you can store your music with no bullshit, a 'music locker'. think Google Play Music, except we won't disappear. currently in early access."
intro_why = "why choose inter.tube?"
intro_1 = "no bullshit. no ads. plain and simple."
intro_2 = "high quality. no re-encoding. flac supported."
intro_3 = "privacy. we don't sell your data."
intro_4 = "fast. lightweight interface. zero bloat."
intro_4-1 = "native app support via the subsonic protocol."
intro_4-2 = "upload songs and edit metadata from your browser, even on mobile."
intro_5 = "we're not google. we won't kill the site."
intro_6 = "run by a real person. always open to user suggestions."
intro_7 = "laid back. lowercase."
intro_howmuch = "how much does it cost?"
intro_pricing = "check out the pricing page"

# register
reg_title = "register account"
reg_intro = "create a new account here. your e-mail will be kept private. it's only for logging in and resetting your password. we won't send marketing bullshit, only important notices regarding your account."
reg_nocc = "no credit card required, cancel anytime."
reg_mustagree = "you must agree to the terms to register"

# index
index_title = "welcome"
index_intro = "this is inter.tube, a place where you can store your music with no bullshit"
index_trialexpired = "your free trial has expired. if you'd like, please subscribe :)"
index_subexpired = "your subscription has expired. please renew here."
index_grandfathered = "we've just launched subscriptions. please consider buying one~"
index_start = "getting started"
index_start_upload = "upload some music"
index_start_library = "view music library"
index_start_buy = "buy a subscription"
index_start_managesub = "manage subscription"
index_start_settings = "settings"
index_more = "more stuff"
index_more_changelog = "changelog"
index_more_subsonic = "native app support via subsonic (beta)"
index_more_sync = "browser sync app (alpha)"
index_more_desktop = "desktop sync app (alpha)"
index_more_forum = "discussion forum"
index_more_help = "need help? e-mail me"
index_app = "desktop app"
index_appexplain = "[11/15] alpha version of desktop syncing has been released."
index_applink = "check it out"
index_news = "news"
index_comingsoon = "coming soonâ„¢"
news_content2 = "[9/28] greetings. i have moved everyone's files to a different storage thing. hopefully it works nicely. i doubled the storage quota so go nuts. lmk if you have any issues @the forums"
news_content = "[9/25] hello everyone. thank you for testing my web site. we are making steady progress towards the Official Launch. feel free to post any thoughts or ideas in the forums. btw, you can check the changelog to see what's new."

# upload
upload_title = "upload tracks"
upload_intro = "use this form or drag & drop music files to upload them to your library. you can select multiple files to upload. you can drag & drop folders. if you click the little check box you can upload whole directories instead of files. currently mp3/flac/m4a only."
upload_full = "storage full"
upload_fullexplain = "you don't have any free space left. please upgrade your plan or delete some files."
upload_cant = "uploading is disabled until you upgrade or free space."
upload_label = "files"
upload_button = "upload"
upload_inprogress = "You still have uploads in progress. Do you want to abandon them?"
upload_skipdupe = "skip duplicates"
enabledirectories = "choose directories instead of files"
# upload status
uploading = "uploading"
preparing = "preparing"
finishing = "finishing"
failedupload = "upload failed :c"
badfiletype = "unsupported filetype. must be mp3/flac/m4a."

# music
music_title = "music library"
music_notracks = "you haven't uploaded any tracks yet."
music_uploadhere = "upload music here"
music_show = "show:"
music_all = "tracks"
music_artists = "artists"
music_albums = "albums"
music_deselect = "deselect"
music_loading = "loading..."

# forum
forum_title = "forum"
forum_intro = "click the link above to go to the forum, hosted on thread zone. you'll have to make a separate account. feel free to post suggestions, bug reports, etc."

# more stuff
more_title = "more stuff"
more_subsonic = "native app support (beta)"
more_subsoniclink = "subsonic API info"
more_subsonicintro = "we now support the subsonic API. there's a lot of good native apps that you can use with inter.tube. some of them have cool features like offline listening. check it out. currently beta with most features implemented."
more_forum = "forum"
more_forumlink = "inter.tube forum"
more_forumintro = "official discussion forum, hosted on thread zone. you'll have to make a separate account. feel free to ask for help, post suggestions, bug reports, etc."
more_changelog = "changelog"
more_changeloglink = "changelog"
more_changelogintro = "info about the latest updates and changes"
more_desktop = "desktop sync app"
more_desktoplink = "desktop sync app (alpha)"
more_desktopintro = "a little app for downloading your entire library to your computer. currently alpha and experimental."
more_support = "support"
more_help = "need help?"
more_helplink = "e-mail me"
more_helpintro = "having trouble? shoot me an e-mail."
more_legal = "legal stuff"

# settings
settings_title = "settings"
settings_intro = "change stuff if you want ğŸ¤ "
settings_actions = "actions"
settings_account = "account"
settings_display = "display"
settings_changepass = "change password"
settings_passchanged = "password successfully changed"
settings_stretch = "stretch"
display_stretch = "stretch track list to full screen width"
settings_musiclink = "library default"
settings_trackview = "track view"
settings_albumview = "album view"
settings_subscription = "subscription"
settings_usage = "usage"
settings_standing = "status"
settings_nextdue = "next charge"
settings_expires = "expires"
settings_update = "update"
settings_renew = "renew"
settings_cancel = "cancel"
settings_expired = "your subscription has expired."
settings_trialexpires = "trial expires"
settings_trialexplain = "your account is currently in free trial mode."
settings_buylink = "check out the plans page to subscribe"
settings_grandfathered = "(early adopter... time TBA)"
settings_storagefull = "you don't have any free space left. please upgrade your plan or delete some files."
settings_trackselect = "track selection"
settings_trackseldefault = "click to select, doubleclick to play"
settings_trackselctrl = "ctrl-click to select, click to play"
settings_payment = "payment method / history"

# forgot
forgot_title = "forgot your password?"
forgot_intro = "we'll send you an e-mail with a link to reset your password."
forgot_send = "send recovery code"
forgot_sent = "success! an e-mail is on the way to {{.v0}}. please check your e-mail for further instructions."

# recover
recover_title = "recover password"
recover_intro = "set a new password for your account"
recover_send = "submit"

# player
player_prev = "previous track"
player_next = "next track"
player_play = "play"
player_pause = "pause"
player_repeat = "repeat"
player_repeat-one = "repeat one track"
player_normal = "repeat disabled"
player_shuffle = "shuffle"
player_download = "download track"
player_edit = "edit track metadata"
player_delete = "delete track"

# edit track
edit_title = "edit track"
edit_changepic = "change picture"
edit_deletepic = "or delete picture"
edit_multiinfo = "editing multiple tracks. leave fields blank to keep them as-is."
edit_spacesep = "(space separated)"

# pricing page
buy_title = "pricing"
buy_monthly = "per month"
buy_subscribe = "subscribe"
buy_intro = "choose a plan based on how much storage space you need. you can upgrade, downgrade, or cancel at any time."
buy_trial = "new accounts include a 14-day 50GB free trial"
buy_trialnow = "you are currently on a 14-day free trial with {{.v0}} days remaining"
buy_trialexpired = "your 14-day free trial has expired"
buy_explain = "payments are handled securely by Stripe. we don't store your credit card info."
buy_subbed = "you are currently subscribed to: {{.v0}}"
buy_grandfathered = "you aren't subscribed to anything"
buy_subexpired = "your subscription has expired"
buy_pitch = "sound good?"
buy_regplz = "" #TODO

# checkout results
checkout_title = "checkout successful"
checkout_thanks = "thank you~"
checkout_explain = "you have successfully subscribed to this plan:"
checkout_settings = "you can confirm, update, or cancel your subscription from the settings page"
# unpaid
checkout_fail = "checkout unsuccessful :("
checkout_failexplain = "we were not able to process your subscription. please double-check your payment info."
checkout_status = "payment status"
checkout_tryagain = "try again?"

# plan names
plan = "plan"
plan_small = "small plan"
plan_big = "the default plan"
plan_huge = "big chungus plan"
plan_ = "(none)"

# privacy policy
privacy_title = "privacy policy"

# ToS
tos_title = "terms of service"
